version: '3.4'

services:
  myweatherserver:
    image: ${DOCKER_REGISTRY-}myweatherserver
    build:
      context: .
      dockerfile: MyWeatherServer/Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0-alpine